#!/usr/bin/env node
console.log("Running test event_emitter");

var multi = require("../lib/testem-multi");
multi.exec(null, "./testem-multi.json");

var messages = [];
var notOk = [];
var ok = [];
multi.on("data", function (message) {
	if (message.indexOf("# Executing") === 0) {
		messages.push(message);
	} else if (message.indexOf("not ok") === 0) {
		notOk.push(message);
	} else if (message.indexOf("ok ") === 0) {
		ok.push(message);
	}
});
multi.on("exit", function (text, details) {
	if (messages.length !== 3) {
		console.error("Expecting 3 test messages, got", messages.length, messages);
		process.exit(1);
	} else if (notOk.length !== 10) {
		console.error("Expecting 3 not ok tests, got", notOk.length, notOk);
		process.exit(10);
	} else if (ok.length !== 10) {
		console.error("Expecting 3 ok tests, got", ok.length, ok);
		process.exit(10);
	} else if (!matchExpectedOutput(text)) {
		console.error("Expecting 4 tests and 2 failures, got", text);
		process.exit(2);
	} else if (!matchExpectedDetails(details)) {
		console.error("Expecting a detail object, got", details);
		process.exit(3);
	} else {
		// All test pass
		process.exit(0);
	}
});

function matchExpectedOutput (out) {
	return out.indexOf("# tests 20") !== -1 &&
		out.indexOf("# pass 10") !== -1 &&
		out.indexOf("# fail 10") !== -1 &&
		out.match(/\nok /g).length === 10 &&
		out.match(/\nnot ok /g).length === 10;
}

function matchExpectedDetails (details) {
	return details.tests === 20 && details.pass === 10 && details.fail === 10 &&
		details.test.length === 20 && details.ok.length === 10 && details.not.length === 10;
}